version: '3'
services:
  app:
    build:
      args:
        user: adam
        uid: 1000
      context: ./php/app
      dockerfile: Dockerfile
    image: my-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8083:80"

  nginx:
    image: nginx:latest
    build:
        context: ./nginx/
        dockerfile: Dockerfile
    volumes:
      - ./conf/:/etc/nginx/conf.d/
    ports:
      - "8081:80"
    links:
      - php
  nginx2:
    image: nginx:latest
    build:
        context: ./nginx/
        dockerfile: Dockerfile
    volumes:
      - ./conf/:/etc/nginx/conf.d/
    ports:
      - "8082:80"
    links:
      - php2
  php:
    build:
        context: ./php/
        dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    links:
      - db
  php2:
    build:
        context: ./php/
        dockerfile: Dockerfile
    ports:
        - "9001:9000"
    volumes:
        - ./app:/var/www/html
    links:
        - db
  db:
    image: mysql:latest
    container_name: mysql-container
    expose:
      - 3306
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb_test
      MYSQL_USER: adib
      MYSQL_PASSWORD: adib
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d